name: docker-build

on:
  schedule:
  - cron:  '0 7 * * *'
  push:
    branches:
    - '**'
    tags:
    - 'v*.*.*'
  pull_request:

jobs:
  build:
    uses: nicholasdille/workflows/.github/workflows/docker-build.yaml@v1.0.0
    with:
      image_name: homebrew
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_PASSWORD }}
