name: docker-build

on:
  schedule:
  - cron:  '0 7 * * *'
  push:
    branches:
    - '**'
    tags:
    - 'v*.*.*'
  pull_request:

jobs:
  build:
    uses: nicholasdille/workflows/docker-build.yaml@v1.0.0-rc.1
